# Generated by Django 2.1.3 on 2018-11-22 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('group_id', models.IntegerField(verbose_name=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to='SecretSanta.Group'))),
                ('name', models.CharField(max_length=255)),
                ('creation', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'families',
            },
        ),
        migrations.CreateModel(
            name='FamilyAdmin',
            fields=[
                ('user_id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))),
                ('family_id', models.IntegerField(blank=True, verbose_name=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to='SecretSanta.Family'))),
                ('admin', models.BooleanField(blank=True)),
            ],
            options={
                'db_table': 'familyadmins',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, null=True)),
                ('creation', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupAdmin',
            fields=[
                ('user_id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))),
                ('group_id', models.IntegerField(blank=True, verbose_name=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to='SecretSanta.Group'))),
                ('admin', models.BooleanField(blank=True)),
            ],
            options={
                'db_table': 'groupadmins',
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('genitive', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'names_genitive',
            },
        ),
        migrations.CreateModel(
            name='Shuffle',
            fields=[
                ('giver', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))),
                ('getter', models.IntegerField(blank=True, verbose_name=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))),
                ('year', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'shuffles',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, verbose_name=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))),
                ('item', models.CharField(blank=True, max_length=1024)),
                ('status', models.IntegerField(blank=True)),
                ('purchased_by', models.IntegerField(null=True, verbose_name=models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))),
            ],
            options={
                'db_table': 'wishlists',
            },
        ),
    ]
