-- Run this script to initialize the tables that are used
-- to look up ID values for different events (audit, shuffle and etc.)
-- Copyright: Taavi Eomäe 2017-2020
-- SPDX-License-Identifier: AGPL-3.0-only